import { createRequire } from 'node:module';
import { mkdir, readFile } from 'node:fs/promises';
import assert from 'node:assert/strict';
const require = createRequire(import.meta.url);
const { chromium } = require(process.env.PLAYWRIGHT_MODULE || 'playwright');
const root = new URL('../../', import.meta.url);
const fixture = JSON.parse(await readFile(new URL('data.json', root), 'utf8'));
delete fixture.buildProjects;
let saved = structuredClone(fixture), saveCount = 0, failSave = false;
const errors = [];
const browser = await chromium.launch({ headless: true });
const context = await browser.newContext({ viewport: { width: 1440, height: 1000 } });
await context.route('**/api/data', async route => {
  if (route.request().method() === 'POST') {
    if (failSave) return route.fulfill({ status: 500, json: { error: 'Simulated save failure' } });
    saved = route.request().postDataJSON(); saveCount++;
    return route.fulfill({ json: { ok: true } });
  }
  return route.fulfill({ json: saved });
});
const page = await context.newPage();
page.on('pageerror', e => errors.push(e.message));
const output = new URL('../../.impeccable/review/', import.meta.url);
await mkdir(output, { recursive: true });
try {
  await page.goto('http://127.0.0.1:8643');
  await page.getByRole('button', { name: 'Incident Command', exact: true }).click();
  await page.getByRole('heading', { name: 'Incident Command', exact: true }).waitFor();
  await page.screenshot({ path: new URL('desktop.png', output).pathname.replace(/^\/(\w:)/, '$1'), fullPage: false });
  const complete = page.getByRole('button', { name: 'Mark step complete' });
  assert.equal(await complete.isDisabled(), true);
  await page.getByLabel('Step status', { exact: true }).selectOption('active');
  for (const checkbox of await page.locator('.build-checks input').all()) await checkbox.check();
  await page.getByLabel('Notes, test results & blockers').fill('Browser test evidence: local services verified.');
  await complete.click();
  await page.getByText('Progress saved', { exact: true }).waitFor();
  assert.ok(saveCount > 0);
  assert.equal(saved.buildProjects['incident-command']['local-startup'].status, 'done');
  assert.deepEqual(saved.books, fixture.books);
  assert.deepEqual(saved.challengeSeries, fixture.challengeSeries);
  await page.reload();
  await page.getByRole('button', { name: 'Incident Command', exact: true }).click();
  await page.getByRole('button', { name: /Start the local workspace/ }).click();
  assert.equal(await page.getByRole('button', { name: '✓ Step verified' }).isDisabled(), true);
  assert.equal(await page.getByLabel('Notes, test results & blockers').inputValue(), 'Browser test evidence: local services verified.');
  await page.locator('.build-checks input').first().uncheck();
  assert.equal(await page.getByLabel('Step status', { exact: true }).inputValue(), 'active');
  assert.equal(await page.getByRole('button', { name: 'Mark step complete' }).isDisabled(), true);
  failSave = true;
  await page.getByLabel('Notes, test results & blockers').fill('Save recovery check');
  await page.getByRole('button', { name: 'retry saving' }).waitFor();
  failSave = false;
  await page.getByRole('button', { name: 'retry saving' }).click();
  await page.getByText('Progress saved', { exact: true }).waitFor();
  await page.getByRole('button', { name: /Document library/ }).click();
  assert.equal(await page.locator('.build-doc-grid > button').count(), 43);
  await page.getByLabel('Search documents').fill('blueprint');
  await page.locator('.build-doc-grid > button').click();
  await page.getByRole('dialog').getByRole('heading', { name: '25 — Build Blueprint' }).waitFor();
  await page.getByRole('dialog').getByRole('button', { name: '03-scope-and-roadmap' }).click();
  await page.getByRole('dialog').getByRole('heading', { name: '03 — Scope and Roadmap' }).waitFor();
  await page.keyboard.press('Escape');
  assert.equal(await page.getByRole('dialog').count(), 0);
  await page.getByRole('button', { name: 'Build journey', exact: true }).click();
  await page.getByLabel('Find a step').fill('nothing-matches-this-query');
  await page.getByRole('button', { name: 'Clear filters' }).click();
  await page.getByRole('button', { name: 'Explore architecture' }).click();
  await page.locator('.build-model canvas').waitFor();
  await page.getByRole('button', { name: 'Spring Boot', exact: true }).click();
  assert.equal(await page.getByRole('button', { name: 'Spring Boot', exact: true }).getAttribute('aria-pressed'), 'true');
  await page.getByText('Own identity, incident state, human approvals and write actions.', { exact: true }).waitFor();
  await page.mouse.move(1100, 430);
  await page.screenshot({ path: new URL('architecture.png', output).pathname.replace(/^\/(\w:)/, '$1'), fullPage: false });
  await page.getByRole('button', { name: 'Quiet motion off' }).click();
  assert.equal(await page.locator('html').getAttribute('data-motion'), 'quiet');
  await page.getByRole('button', { name: 'Hide architecture' }).click();
  const [download] = await Promise.all([page.waitForEvent('download'), page.getByRole('button', { name: 'Export progress ↓' }).click()]);
  assert.equal(download.suggestedFilename(), 'incident-command-progress.json');
  await page.setViewportSize({ width: 390, height: 844 });
  await page.evaluate(() => window.scrollTo(0, 0));
  await page.screenshot({ path: new URL('mobile.png', output).pathname.replace(/^\/(\w:)/, '$1'), fullPage: false });
  assert.ok(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth + 1), 'No mobile horizontal overflow');
  await page.getByRole('button', { name: /Document library/ }).click();
  await page.getByLabel('Search documents').fill('blueprint');
  await page.locator('.build-doc-grid > button').click();
  await page.getByRole('dialog').getByRole('heading', { name: '25 — Build Blueprint' }).waitFor();
  await page.screenshot({ path: new URL('mobile-reader.png', output).pathname.replace(/^\/(\w:)/, '$1'), fullPage: false });
  await page.keyboard.press('Escape');
  assert.equal(await page.locator('.build-doc-grid > button').evaluate(el => el === document.activeElement), true, 'Reader restores trigger focus');
  await page.emulateMedia({ reducedMotion: 'reduce' });
  await page.reload();
  await page.getByRole('heading', { name: 'Incident Command', exact: true }).waitFor();
  assert.equal(await page.locator('html').getAttribute('data-motion'), 'quiet');
  assert.deepEqual(errors, []);
  console.log(JSON.stringify({ result: 'PASS', saveCount, checks: ['completion gating', 'persist/reload', 'preserve books/challenges', 'reopen', 'save failure/retry', '43 documents', 'cross-document navigation', 'Escape and focus restoration', 'search', '3D selection', 'quiet and OS reduced motion', 'export', 'mobile reader/overflow', 'bookmark route', 'no runtime errors'] }, null, 2));
} finally { await browser.close(); }
