import { createRequire } from 'node:module';
import { mkdir, readFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import assert from 'node:assert/strict';
import { Euler, PerspectiveCamera, Vector3 } from 'three';
import { chapterPoint, facingRotation } from '../src/utils/chapterNavigation.js';
const require = createRequire(import.meta.url);
const { chromium } = require(process.env.PLAYWRIGHT_MODULE || 'playwright');
const fixture = JSON.parse(await readFile(new URL('../../data.json', import.meta.url), 'utf8'));
const output = new URL('../../.impeccable/review/', import.meta.url);
await mkdir(output, { recursive: true });
const browser = await chromium.launch({ headless: true });
const errors = [];
async function createPage(options = {}) {
  const context = await browser.newContext({ viewport: { width: 1440, height: 1000 }, ...options });
  let saved = structuredClone(fixture);
  await context.route('**/api/data', route => {
    if (route.request().method() === 'POST') { saved = route.request().postDataJSON(); return route.fulfill({ json: { ok: true } }); }
    return route.fulfill({ json: saved });
  });
  const page = await context.newPage();
  page.on('pageerror', error => errors.push(error.message));
  await page.goto('http://127.0.0.1:8643/#/projects/incident-command');
  if (options.isMobile) await page.getByRole('button', { name: 'Toggle navigation' }).click();
  await page.getByRole('button', { name: fixture.books[0].name, exact: true }).click();
  await page.locator('.chapter-line').first().waitFor();
  await page.waitForTimeout(650);
  return { page, context, saved: () => saved };
}
async function shot(page, name, fullPage = true) {
  if (process.env.NAV_CAPTURE === '0') return;
  if (process.env.NAV_CAPTURE === 'review' && !name.includes('library')) return;
  await page.evaluate(() => window.scrollTo(0, 0));
  await page.waitForTimeout(450);
  await page.screenshot({ path: fileURLToPath(new URL(name, output)), fullPage });
}
try {
  const { page, saved } = await createPage();
  assert.equal(await page.getByRole('button', { name: 'List', exact: true }).getAttribute('aria-pressed'), 'true');
  const initialBooks = structuredClone(saved().books);
  await page.getByLabel('Search chapters').fill('orientation');
  await shot(page, 'navigation-list-desktop.png');
  await page.getByRole('button', { name: 'Rocket route', exact: true }).click();
  await page.locator('.route-rocket[transform]').waitFor({ state: 'attached' });
  await shot(page, 'navigation-rocket-desktop.png');
  const before = await page.locator('.route-rocket').getAttribute('transform');
  await page.evaluate(() => window.scrollTo(0, document.body.scrollHeight));
  await page.waitForTimeout(300);
  assert.notEqual(await page.locator('.route-rocket').getAttribute('transform'), before);
  assert.deepEqual(saved().books, initialBooks, 'Browsing must not mark chapters complete');
  await page.getByLabel('Search chapters').fill('');
  await page.getByRole('button', { name: 'Chapter globe', exact: true }).click();
  await page.locator('.learning-scene[data-ready="true"] canvas').waitFor();
  await page.waitForTimeout(700);
  await shot(page, 'navigation-globe-desktop.png');
  // Click an actual front-facing mesh, not just its accessible native equivalent.
  await page.locator('.learning-scene').scrollIntoViewIfNeeded();
  const bounds = await page.locator('.learning-scene canvas').boundingBox();
  const [, selectedPart, selectedTopic] = (await page.getByLabel('Choose a chapter').inputValue()).split(':').map((value, i) => i ? Number(value) : value);
  const parts = fixture.books[0].parts;
  const initialPoint = chapterPoint(selectedPart, selectedTopic, parts.length, parts[selectedPart].topics.length);
  const camera = new PerspectiveCamera(44, bounds.width / bounds.height, .1, 1000);
  camera.position.z = 5.6; camera.updateMatrixWorld();
  const point = new Vector3(...chapterPoint(2, 0, parts.length, parts[2].topics.length)).applyEuler(new Euler(...facingRotation(initialPoint))).project(camera);
  await page.mouse.click(bounds.x + (point.x + 1) * bounds.width / 2, bounds.y + (1 - point.y) * bounds.height / 2);
  assert.equal(await page.getByLabel('Choose a chapter').inputValue(), 'ssh:2:0');
  await page.getByLabel('Choose a chapter').selectOption('ssh:1:2');
  const selectedTitle = fixture.books[0].parts[1].topics[2].title;
  assert.equal(await page.locator('.globe-selection h2').textContent(), selectedTitle);
  await page.getByRole('button', { name: 'Read chapter', exact: false }).click();
  await page.getByRole('dialog', { name: selectedTitle, exact: true }).waitFor();
  await page.getByRole('button', { name: 'Close', exact: true }).click();
  await page.getByRole('dialog').waitFor({ state: 'hidden' });
  assert.equal(await page.getByLabel('Choose a chapter').inputValue(), 'ssh:1:2');
  const statusButton = page.locator('.globe-detail .chapter-state');
  const statusLabel = await statusButton.getAttribute('aria-label');
  const previousStatus = saved().books[0].parts[1].topics[2].status;
  await statusButton.click();
  await page.waitForTimeout(1200);
  assert.notEqual(await statusButton.getAttribute('aria-label'), statusLabel);
  assert.equal(saved().books[0].parts[1].topics[2].status, { not_started: 'in_progress', in_progress: 'done', done: 'not_started' }[previousStatus]);
  await page.getByLabel('Search chapters').fill('no-chapter-matches-this');
  await page.getByRole('heading', { name: 'No chapters found' }).waitFor();
  assert.equal(await page.locator('.learning-scene canvas').count(), 0);
  await page.getByRole('button', { name: 'Clear filters' }).click();
  await page.getByRole('button', { name: 'Chapter cards', exact: true }).click();
  await page.locator('.quest-node').first().waitFor();
  await page.getByRole('button', { name: 'Constellation map', exact: true }).click();
  await page.locator('.map-node').first().waitFor();
  await page.getByRole('button', { name: 'Learning library', exact: false }).click();
  await page.getByRole('button', { name: 'Orbital library', exact: true }).click();
  await page.locator('.orbital-library .learning-scene[data-ready="true"] canvas').waitFor();
  await page.locator('.orbital-library').evaluate(element => window.scrollTo(0, element.getBoundingClientRect().top + scrollY - 110));
  await page.waitForTimeout(200);
  const firstOrbitBook = await page.getByLabel('Choose a book').inputValue();
  await page.evaluate(() => window.scrollBy(0, 750));
  await page.waitForTimeout(200);
  assert.notEqual(await page.getByLabel('Choose a book').inputValue(), firstOrbitBook);
  await page.locator('.orbital-library').scrollIntoViewIfNeeded();
  const beforePause = await page.locator('.orbit-library-stage').boundingBox();
  await page.getByRole('button', { name: 'Pause scroll browsing' }).click();
  await page.waitForTimeout(100);
  const pausedStage = await page.locator('.orbit-library-stage').boundingBox();
  assert.ok(Math.abs(pausedStage.y - beforePause.y) < 3, `Pausing must preserve stage y (${beforePause.y} to ${pausedStage.y})`);
  if (process.env.NAV_CAPTURE !== '0') await page.screenshot({ path: fileURLToPath(new URL('navigation-library-deep-pause-desktop.png', output)) });
  await page.getByRole('button', { name: 'Resume scroll browsing' }).click();
  await page.locator('.orbital-library').evaluate(element => window.scrollTo(0, element.getBoundingClientRect().top + scrollY + 650));
  await page.waitForTimeout(150);
  const beforeSelection = await page.locator('.orbit-library-stage').boundingBox();
  await page.getByLabel('Choose a book').selectOption('ai');
  await page.waitForTimeout(100);
  const afterSelection = await page.locator('.orbit-library-stage').boundingBox();
  assert.ok(Math.abs(afterSelection.y - beforeSelection.y) < 3, `Manual selection must preserve stage y (${beforeSelection.y} to ${afterSelection.y})`);
  if (process.env.NAV_CAPTURE !== '0') await page.screenshot({ path: fileURLToPath(new URL('navigation-library-deep-selection-desktop.png', output)) });
  assert.equal(await page.locator('.orbit-book-copy h3').textContent(), fixture.books[1].name);
  await shot(page, 'navigation-library-desktop.png');
  await page.getByRole('button', { name: 'Explore this book' }).click();
  await page.getByRole('heading', { name: fixture.books[1].name, exact: true }).waitFor();

  const mobile = await createPage({ viewport: { width: 390, height: 844 }, isMobile: true, hasTouch: true, reducedMotion: 'reduce' });
  await mobile.page.getByLabel('Search chapters').fill('orientation');
  await shot(mobile.page, 'navigation-list-mobile.png');
  await mobile.page.getByRole('button', { name: 'Rocket route', exact: true }).click();
  await mobile.page.locator('.route-rocket[transform]').waitFor({ state: 'attached' });
  await shot(mobile.page, 'navigation-rocket-mobile.png');
  const parked = await mobile.page.locator('.route-rocket').getAttribute('transform');
  await mobile.page.evaluate(() => window.scrollTo(0, document.body.scrollHeight));
  await mobile.page.waitForTimeout(200);
  assert.equal(await mobile.page.locator('.route-rocket').getAttribute('transform'), parked);
  await mobile.page.getByRole('button', { name: 'Chapter globe', exact: true }).click();
  await mobile.page.locator('.learning-scene[data-ready="true"] canvas').waitFor();
  await shot(mobile.page, 'navigation-globe-mobile.png');
  assert.equal(await mobile.page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true);
  await mobile.page.getByRole('button', { name: 'Learning library', exact: false }).click();
  await mobile.page.getByRole('button', { name: 'Orbital library', exact: true }).click();
  await mobile.page.locator('.orbital-library .learning-scene[data-ready="true"] canvas').waitFor();
  await shot(mobile.page, 'navigation-library-mobile.png');
  assert.equal(await mobile.page.getByRole('button', { name: 'Pause scroll browsing' }).count(), 0);
  assert.equal(await mobile.page.evaluate(() => document.documentElement.scrollWidth <= innerWidth), true);

  // A lost rendering context leaves native selection and the reader available.
  await mobile.page.getByRole('button', { name: 'Explore this book' }).click();
  await mobile.page.getByRole('button', { name: 'Chapter globe', exact: true }).click();
  await mobile.page.locator('.learning-scene[data-ready="true"] canvas').evaluate(canvas => canvas.dispatchEvent(new Event('webglcontextlost')));
  await mobile.page.getByText('3D view unavailable', { exact: true }).waitFor();
  assert.equal(await mobile.page.getByRole('button', { name: 'Read chapter', exact: false }).isEnabled(), true);

  const noGL = await browser.newContext({ viewport: { width: 1000, height: 800 } });
  await noGL.addInitScript(() => {
    const original = HTMLCanvasElement.prototype.getContext;
    HTMLCanvasElement.prototype.getContext = function(kind, ...args) { return kind.startsWith('webgl') ? null : original.call(this, kind, ...args); };
  });
  await noGL.route('**/api/data', route => route.fulfill({ json: route.request().method() === 'POST' ? { ok: true } : fixture }));
  const fallbackPage = await noGL.newPage();
  await fallbackPage.goto('http://127.0.0.1:8643/#/projects/incident-command');
  await fallbackPage.getByRole('button', { name: fixture.books[0].name, exact: true }).click();
  await fallbackPage.getByRole('button', { name: 'Chapter globe', exact: true }).click();
  await fallbackPage.getByText('3D view unavailable', { exact: true }).waitFor();
  await fallbackPage.getByLabel('Choose a chapter').selectOption('ssh:1:2');
  await fallbackPage.getByRole('button', { name: 'Read chapter', exact: false }).focus();
  await fallbackPage.keyboard.press('Enter');
  await fallbackPage.getByRole('dialog', { name: selectedTitle, exact: true }).waitFor();
  assert.deepEqual(errors, []);
  console.log('PASS: list, native-scroll rocket, globe selection/reader/status, saved indices, legacy views, orbital library, mobile, quiet mode, context-loss fallback.');
} finally { await browser.close(); }
